import { ChakraProvider } from "@chakra-ui/react";
import localFont from "next/font/local";
import "./globals.css";
import Layout from "./components/Layout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          <Layout>{children}</Layout>
        </ChakraProvider>
      </body>
    </html>
  );
}
